# Generated by Django 5.2.8 on 2025-12-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcycle',
            name='notes',
        ),
    ]
