# Generated by Django 5.2.8 on 2025-12-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_remove_trainingcycle_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcycletheme',
            name='target_elo',
        ),
    ]
