# Generated by Django 5.2.8 on 2025-12-18 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_remove_trainingcycletheme_target_elo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingcycle',
            old_name='completed_exercises',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='trainingcycle',
            old_name='total_exercises',
            new_name='total',
        ),
    ]
