# Generated by Django 5.2.8 on 2025-12-18 03:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_rename_completed_exercises_trainingcycle_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeexercise',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='puzzleattempt',
            name='time_spent',
        ),
        migrations.RemoveField(
            model_name='trainingpreferences',
            name='time_limit_seconds',
        ),
        migrations.AddField(
            model_name='activeexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
