# Generated by Django 5.2.8 on 2025-12-18 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_remove_activeexercise_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetryPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_id', models.CharField(max_length=100)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='puzzletraining',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='puzzletraining',
            name='theme_origin',
        ),
        migrations.RemoveField(
            model_name='puzzletraining',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainingstreak',
            name='user',
        ),
        migrations.RenameField(
            model_name='puzzleattempt',
            old_name='theme_origin',
            new_name='theme',
        ),
        migrations.RenameField(
            model_name='trainingcycle',
            old_name='completed',
            new_name='completed_puzzles',
        ),
        migrations.AlterUniqueTogether(
            name='dailyprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='themeelo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='trainingcycletheme',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='trainingcycle',
            name='total',
        ),
        migrations.AddField(
            model_name='trainingcycle',
            name='total_puzzles',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='elo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='puzzleattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='themeelo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_elos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingcycle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='puzzleattempt',
            index=models.Index(fields=['user', 'created_at'], name='chess_puzzl_user_id_801876_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzleattempt',
            index=models.Index(fields=['puzzle_id'], name='chess_puzzl_puzzle__720cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='themeelo',
            index=models.Index(fields=['user'], name='chess_theme_user_id_8e0b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='themeelo',
            index=models.Index(fields=['theme'], name='chess_theme_theme_i_9d2f1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyprogress',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_day'),
        ),
        migrations.AddConstraint(
            model_name='themeelo',
            constraint=models.UniqueConstraint(fields=('user', 'theme'), name='unique_user_theme_elo'),
        ),
        migrations.AddConstraint(
            model_name='trainingcycletheme',
            constraint=models.UniqueConstraint(fields=('cycle', 'theme'), name='unique_cycle_theme'),
        ),
        migrations.AddField(
            model_name='retrypuzzle',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chess.theme'),
        ),
        migrations.AddField(
            model_name='retrypuzzle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_puzzles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PuzzleTraining',
        ),
        migrations.DeleteModel(
            name='TrainingStreak',
        ),
        migrations.AddConstraint(
            model_name='retrypuzzle',
            constraint=models.UniqueConstraint(fields=('user', 'puzzle_id'), name='unique_retry_puzzle'),
        ),
    ]
