# Generated by Django 5.2.8 on 2025-12-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0006_retrypuzzle_alter_puzzletraining_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_trainable',
            field=models.BooleanField(default=True, help_text='Indica si el tema puede ser asignado a ciclos de entrenamiento'),
        ),
    ]
