# Generated by Django 5.2.8 on 2025-12-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0007_theme_is_trainable'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del tema y qué habilidad desarrolla'),
        ),
    ]
