# Generated by Django 5.2.8 on 2025-12-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0008_theme_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzleattempt',
            name='theme',
        ),
    ]
