# Generated by Django 5.2.8 on 2025-12-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0009_remove_puzzleattempt_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='theme',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Categoría padre (otro Theme)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subthemes', to='chess.theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del tema o categoría'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='is_trainable',
            field=models.BooleanField(default=True, help_text='Indica si el tema puede ser entrenado directamente'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='lichess_name',
            field=models.CharField(blank=True, help_text='Nombre del tema en Lichess (solo para temas entrenables)', max_length=100, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='DailyProgress',
        ),
    ]
