# Generated by Django 5.2.8 on 2025-12-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0010_alter_theme_options_theme_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeelo',
            name='last_trained',
            field=models.DateTimeField(blank=True, help_text='Última vez que este tema fue entrenado por el usuario', null=True),
        ),
    ]
