# Generated by Django 5.2.8 on 2025-12-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0011_themeelo_last_trained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeelo',
            name='last_trained',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que este tema fue entrenado por el usuario', null=True),
        ),
    ]
