# Generated by Django 5.2.8 on 2025-12-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0012_alter_themeelo_last_trained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcycle',
            name='total_puzzles',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
